m = int(input("Enter the first number: "))
n = int(input("Enter the second number: "))
# x=int(m)
# y=int(n)
print("Addition of",m , "and", n , "is" , m+n )
print("Subtraction of ", m, "and",n , "is", m-n)
print("Muliplication of", m, "and", n , "is", m*n)
print("Divison of", m, "by", n, "is", m/n)
print("Floor / Integer divison of", m, "by", n, "is", m//n)
print("Remainder of ", m, "by", n, "is", m%n)
print("Power of", m,"to", n ,"is", m**n)
